### ISSUE TITLE
Add useService hook

### ISSUE THREAD

**Issue by batusai513** [matthewp/react-robot#5]
This is needed to make the react integration work with serialised machines as [indicated here](https://thisrobot.life/guides/comparison-with-xstate.html#serialization-deserialization).

Thanks for this project, looks very promising 👍

**Comment by matthewp** [comment]
Hi @batusai513, the `useMachine` creates services for you. If you are looking to integrate that pattern in a React app you can do so like this:

```js
import { interpret } from 'robot3';
import React from 'react';
import { useMachine } from 'react-robot';
import machine from './some-machine.js';

const currentState = JSON.parse(localState.appState);

// Extend the defined machine setting the current state.
const currentMachine = Object.create(machine, {
  current: { value: currentState.name },
  context: {
    value: () => currentState.context
  }
});

function Counter() {
  const [current, send] = useMachine(currentMachine);

  ...
}
```

**Comment by batusai513** [comment]
@matthewp That worked without issues, Thanks for your help and for this package. 🥇
