### ISSUE TITLE
Can't perform a React state update on an unmounted component

### ISSUE THREAD

**Issue by tschaub** [matthewp/react-robot#9]
Thanks for your work on this project!  The documentation is great and the API feels really nice.

I'm trying to use the `useMachine` hook on a component that unmounts as a result of a state transition.  In my application, I'm using the `navigate` function from [hookrouter](https://www.npmjs.com/package/hookrouter), but I imagine the same issue would come up with other applications.

When I `invoke` a function or use an `action` that triggers a navigation, I get the following:

```
Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
```

This comes from the `onChange` call here: https://github.com/matthewp/robot/blob/v0.2.9/machine.js#L170

I can accomplish what I want with `setTimeout`, but I'm wondering if there is a better way.
```
createMachine({
  navigating: invoke(async () => {
    // without this timeout, the component updates after unmount
    setTimeout(() => {
      navigate('/some/other/path');
    });
  })
});
```

Is there a `useEffect` callback that could be doing some more cleanup?

**Comment by matthewp** [comment]
This is now available via `robot-hooks` 0.3.2 so should come with react-robot. Thanks so much for the contribution!
